In [1]:
from ultralytics import YOLO
import cv2
import os
import urllib

c:\Users\jeongjin\anaconda3\envs\yolov8\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# download image
os.makedirs('data', exist_ok=True)
urllib.request.urlretrieve("https://ultralytics.com/images/bus.jpg", 'data/bus.jpg')

('data/bus.jpg', <http.client.HTTPMessage at 0x1999eb3ef70>)

In [3]:
# load model
# model = YOLO("yolov8s.yaml")
model = YOLO("./pretrained/yolov8s.pt")

In [4]:
model.train(cfg="cfg/custom.yaml")

cfg file passed. Overriding default params with cfg/custom.yaml.
Ultralytics YOLOv8.0.51  Python-3.9.16 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
yolo\engine\trainer: task=detect, mode=train, model=pretrained/yolov8s.pt, data=dataset/coco128.yaml, epochs=1, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=runs/custom, name=rhee, exist_ok=True, pretrained=True, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_mas

In [6]:
# validation
metrics = model.val()

Ultralytics YOLOv8.0.51  Python-3.9.16 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
val: Scanning C:\Users\jeongjin\Desktop\rhee\velog_yolov8_tutorial\datasets\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:24<00:00,  3.07s/it]
                   all        128        929      0.813      0.678       0.77      0.594
                person        128        254       0.93      0.681      0.828      0.628
               bicycle        128          6          1      0.314       0.44      0.267
                   car        128         46      0.805      0.217      0.406      0.227
            motorcycle        128          5      0.825          1      0.928      0.753
              airplane        128          6       0.88          1      0.995      0.859
                   bus        128    

In [10]:
# load image
img = cv2.imread("data/bus.jpg", cv2.IMREAD_COLOR)
results = model(source=img)
print(results)


0: 640x480 4 persons, 1 bus, 108.1ms
Speed: 2.0ms preprocess, 108.1ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)


[{ '_keys': <generator object Results.__init__.<locals>.<genexpr> at 0x0000019A7636E4A0>,
  'boxes': ultralytics.yolo.engine.results.Boxes
type:  torch.Tensor
shape: torch.Size([5, 6])
dtype: torch.float32
tensor([[2.00000e+01, 2.29000e+02, 8.05000e+02, 7.49000e+02, 9.20059e-01, 5.00000e+00],
        [6.67000e+02, 3.89000e+02, 8.10000e+02, 8.80000e+02, 8.90183e-01, 0.00000e+00],
        [5.00000e+01, 4.00000e+02, 2.45000e+02, 9.03000e+02, 8.82242e-01, 0.00000e+00],
        [2.21000e+02, 4.08000e+02, 3.46000e+02, 8.61000e+02, 8.70849e-01, 0.00000e+00],
        [0.00000e+00, 5.50000e+02, 6.70000e+01, 8.68000e+02, 6.05244e-01, 0.00000e+00]], device='cuda:0'),
  'masks': None,
  'names': { 0: 'person',
             1: 'bicycle',
             2: 'car',
             3: 'motorcycle',
             4: 'airplane',
             5: 'bus',
             6: 'train',
             7: 'truck',
             8: 'boat',
             9: 'traffic light',
             10: 'fire hydrant',
             11: 'sto

In [12]:
boxes = results[0].boxes
box = boxes[0]  # returns one box
print(box.xyxy)
print(box.conf)

tensor([[ 20., 229., 805., 749.]], device='cuda:0')
tensor([0.92006], device='cuda:0')


In [7]:
success = model.export(format="onnx")

Ultralytics YOLOv8.0.51  Python-3.9.16 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)

PyTorch: starting from runs\custom\rhee\weights\best.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (21.5 MB)
requirements: YOLOv8 requirement "onnx>=1.12.0" not found, attempting AutoUpdate...
     --------------------------------------- 12.2/12.2 MB 72.5 MB/s eta 0:00:00
     ---------------------------------------- 904.2/904.2 kB ? eta 0:00:00

requirements: 1 package updated per ['onnx>=1.12.0']
requirements:  Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.13.1...
ONNX: export success  6.8s, saved as runs\custom\rhee\weights\best.onnx (42.7 MB)

Export complete (6.9s)
Results saved to C:\Users\jeongjin\Desktop\rhee\velog_yolov8_tutorial\runs\custom\rhee\weights
Predict:         yolo predict task=detect model=runs\custom\rhee\weights\best.onnx imgsz=640 
Validate:        yolo val task=detect model=runs\c